### ISSUE TITLE
Manuelle Installation / Manual Installation

### ISSUE THREAD

**Issue by designpilot** [ErdmannFreunde/calendar_feature#1]
Ich musste die Erweiterung **calendar_feature** in **Contao 4.4.2** manuell installieren (im CM war diese zwar für die Installation ersichtlich "ohne Hinweis das diese nicht kompatibel sei" aber konnte nicht über den CM installiert werden, da in betreffender Datei der Versionshinweis fehlt).

**Manuelle Installation:**
- den entpackten ZIP Ordner "euf_overlay-master" von GitHub umbenennen in "euf_overlay"
- den Ordner "euf_overlay" auf den Webserver in das Verzeichnis ./system/modules laden
- im CM auf Systemwartung -> Cache neu erstellen
- im CM auf Tools und auf den Link für das Installtool klicken
- im Installtool die DB aktualisieren

Soweit ist die Installation sauber durchgelaufen, ich konnte es aber im BE und FE noch nicht testen da es eine frische Installation ist.

------------------------------------------------------------------------------------------------

I had to install the extension **calendar_feature** in **Contao 4.4.2** manually (in the CM it was shown for the installation "without notice this is not compatible" but could not be installed via the CM because the corresponding file is missing the version hints).

**Manual installation:**
- Rename the unpacked ZIP folder "euf_overlay-master" from GitHub to "euf_overlay"
- Load the folder "euf_overlay" on the web server in the directory ./system/modules
- In CM on System Maintenance -> Rebuild Cache
- In CM on Tools click on the link for the install tool
- In the install tool update the DB

As far as the installation went through cleanly, but I could not test it (it is a fresh installation).

**Comment by bastibuck** [comment]
Danke für den Hinweis, bitte teste doch auch nochmal die Funktionalität im FE, dann können wir eine neue Version mit Contao 4.x freigeben.

**Comment by wortberge** [comment]
Weiterhin muss die Erweiterung manuell installiert werden. Bei den einzelnen Events ist die Checkbox "Termin hervorheben" in den Einstellungen vorhanden, in der Datenbank ist die Spalte 'featured' angelegt und wird befüllt.

Einzig bei der Ausgabe fehlen im Listenmodul die Auswahlmöglichkeiten für die Anzeigensteuerung. Das liegt an der Ersetzung in der calendar_feature/dca/tl_module.php
perPage ist nicht mehr der letzte Eintrag der Palette und wird demnach als 'perPage;' nicht mehr gefunden.

**Comment by denniserdmann** [comment]
@wortberge Danke für den Hinweis. Dadurch habe ich den Fehler nun recht schnell beheben können. 

Außerdem lässt sich die Erweiterung nun auch unter Contao 4.4 installieren.
