### ISSUE TITLE
Migrate to Contao 4.10+

### ISSUE THREAD

**Issue by rabauss** [ErdmannFreunde/calendar_feature#11]
Since Contao 4.10 the featured events have been part of the contao core, so you no longer need this extension.

If you want to migrate your modules, I can recommend my migration:
https://gist.github.com/rabauss/b659ad363d634cfb8bca1a7eaad6d430

**Comment by denniserdmann** [comment]
i haven't tried it yet, but if it works as expected, i would appreciate it, if you would turn it into an PR, too

**Comment by rabauss** [comment]
Well, but should I add the migration to this extension? normally you would uninstall this extension while updating to contao 4.10+ or we need a migration extension. And I remove the column `events_featured` in `tl_module` to know that the migration was executed successfully!

**Comment by denniserdmann** [comment]
You're right. A composer option „run migration and delete extension, if XY is true“ would be the best solution. I think i will update the readme and link to your gist. Can you describe how to run the migration script in your gist, too?

**Comment by rabauss** [comment]
In favor of my small extension I removed the gist - see now:
https://github.com/bwein-net/contao-migrate-calendar-feature
