### ISSUE TITLE
Contao 4 Kompatibilität

### ISSUE THREAD

**Issue by akroii** [ErdmannFreunde/calendar_feature#2]
Könnt Ihr bitte diese Erweiterung für Contao 4 erweitern?

**Comment by denniserdmann** [comment]
Ich schaue mal, ob ich den im anderen Ticket erwähnten Fehler erstmal beheben kann, damit die Erweiterung grundsätzlich unter Contao 4 wieder funktioniert. Eine Umsetzung als Bundle ist erstmal nicht geplant.

**Comment by denniserdmann** [comment]
Sollte nun funktionieren. Bitte mal prüfen.
