### ISSUE TITLE
Calendar Feature mit eigener Erweiterung erweitern

### ISSUE THREAD

**Issue by denniserdmann** [ErdmannFreunde/calendar_feature#5]
Folgende Supportanfrage kam per Mail:

> ich nutze eure Erweiterung Calendar_feature in Contao 4.
Jetzt möchte ich eure Funktionalität noch um eine eigene Funktion erweitern, in der Art
class EventsFeature extends \Controller
{
  public function getMyFormats(DataContainer $dc)...
}
leider verliert er dadurch eure Funktion "getFeaturedEvents" in welchem Namespace befindet sich eure Klasse "EventsFeature". Ich wäre euch sehr dankbar, wenn ihr mich von dem Schlauch schubsen könntet auf dem ich vermutlich grad stehe. Für eine Core Erweiterung hab ich das in ähnlicher Art geschafft. use Contao\Events as CoreClass_Events;
abstract class Events extends CoreClass_Events

**Comment by bastibuck** [comment]
Unsere Klasse liegt in keinem Namespace. Wir nutzen einen Core-Hook der in der config/config.php registriert ist. 
Je nach was geplant ist, kann man einfach einen weiteren Hook registrieren. Die dürften nacheinander (Ladereihenfolge!) abgearbeitet werden.

Unsere Klasse sollte man sonst genau so erweitern können wie im Beispiel, aber dann wird man auch einen Hook registrieren müssen, der die neue Klasse implementiert und unsere alte Methode dort aufrufen oder wie gesagt einen zweiten Hook.
(Alles ungetestet und aus dem Kopf geschrieben).
