### ISSUE TITLE
BE: Listenansicht Termine: Klick auf "Hervorheben-Icon" ist kein AJAX-Request

### ISSUE THREAD

**Issue by trilobit-gmbh** [ErdmannFreunde/calendar_feature#6]
Contao 4.4.20
Keine weiteren Erweiterungen/Bundles die die Events erweitern/ergänzen/anpassen

**Comment by denniserdmann** [comment]
Bei mir funktioniert das Hervorheben über das Icon ohne Probleme. Falls dir Fehler bei dir noch auftritt, bekommst du einen Hinweis in der Konsole, über den sich das Problem eingrenzen lässt?

**Comment by trilobit-gmbh** [comment]
**Infos**

(/) Das Hervorheben bei Klick auf das Icon in der Übersicht funktioniert.
(!) Die Option wird jedoch nicht als AJAX-Request ausgeführt (z.B. analog dem Klick auf das "Auge"), sondern die Listenseite wird bei jedem Klick neu geladen.
In den Developer-Tools sehe ich (im Gegensatz zu den News) keinen XHR-Request.


(i) Ich konnte den Fehler folgendermaßen eingrenzen:

Ändere ich den Aufruf "return AjaxRequest.tl_calendar_feature.toggleFeatured(this,%s)" nach "return AjaxRequest.toggleFeatured(this,%s)" wird versucht, die Klasse aus "tl_calendar_events" zu triggern.

Packe ich testweise deine Methode hierzu in die Core-DCA wird sie von "./vendor/contao/core-bundle/src/Resources/contao/classes/Ajax.php" gefunden und getriggert >> alles OK

Im Orginalfall wird der Link aufgerufen und kein XHR.

Klicke ich auf das Icon und breche dann die Aktion mit [ESC] ab finde ich folgende Meldung in der Console:
```
Uncaught TypeError: Cannot read property 'toggleFeatured' of undefined
    at HTMLAnchorElement.onclick (contao?do=calendar&table=tl_calendar_events&id=1&rt=zKnMMjLuHHw0sD6rDkszVET-kbYhvaUh8EGm6pwy5do&ref=IflQ1v7_:287)
```

Der Fehler tritt in der core.js auf. Dort gibt es die Funktion "AjaxRequest.tl_calendar_feature.toggleFeatured" nicht - nur "AjaxRequest.toggleFeatured"

Im Prinzip musst Du jetzt das AjaxRequest-Objekt aus der core.js ergänzen, damit dein Aufruf im JS verarbeitet werden kann. Im eigentlichen AJAX-Request muss die Action angepasst werden, damit das Ajax.php den Aufruf korrekt abarbeiten kann.

```
var AjaxRequest =
{
...
    tl_calendar_feature: {
        toggleFeatured: function(el, id) {
            el.blur();

            var image = $(el).getFirst('img'),
                featured = (image.get('data-state') == 1);

            // Backwards compatibility
            if (image.get('data-state') === null) {
                featured = (image.src.indexOf('featured_') == -1);
                window.console && console.warn('Using a featured toggle without a "data-state" attribute is deprecated. Please adjust your Contao DCA file.');
            }

            // Send the request
            if (!featured) {
                image.src = AjaxRequest.themePath + 'icons/featured.svg';
                image.set('data-state', 1);
                new Request.Contao().post({'action':'toggleFeaturedEvents', 'id':id, 'state':1, 'REQUEST_TOKEN':Contao.request_token});
            } else {
                image.src = AjaxRequest.themePath + 'icons/featured_.svg';
                image.set('data-state', 0);
                new Request.Contao().post({'action':'toggleFeaturedEvents', 'id':id, 'state':0, 'REQUEST_TOKEN':Contao.request_token});
            }

            return false;
        }
    }
...
};
```

Danach wird der Aufruf korrekt via AJAX-Request abgesetzt. Jetzt muss "nur" noch die Core-Ajax-Klasse mit dem Aufruf etwas anfangen können.
Hierzu müsste der switch case Aufruf aus "Ajax::executePostActions" ergänzt werden.

```
// Feature/unfeature an element
case 'toggleFeaturedEvents':
    $dc->table = 'tl_calendar_feature';

    if (class_exists($dc->table, false))
    {
        $dca = new $dc->table();

        if (method_exists($dca, 'toggleFeatured'))
        {
            $dca->toggleFeatured(\Input::post('id'), ((\Input::post('state') == 1) ? true : false));
        }
    }

    throw new NoContentResponseException();
```

Am Einfachsten wäre sicher einen Pull-Request zu machen bei dem in der Orginal DCA-Klasse von "tl_calendar_events" die Methode "toggleFeatured" ergänzt werden würde. Dann könntest Du das "attributes" Feld in der DCA wie folgt schreiben:

```
'attributes' => 'onclick="Backend.getScrollOffset();return AjaxRequest.toggleFeatured(this,%s)"',
```

Gerne kannst Du mich auch direkt kontaktieren bei Fragen hierzu (peter.adelmann@trilobit.de).

Jetzt weiß ich zumindest wo der "Fehler" liegt und was notwendig wäre um das Verhalten zu ändern.
Wenn ich das so sehe kann ich wohl auch erst einmal "gut" damit leben so wie es ist ;-)

Viele Grüße
Peter

**Comment by denniserdmann** [comment]
Danke für die die sehr ausführliche Erklärung. Mir ist es ehrlich gesagt auch gar nicht aufgefallen, dass es kein Ajax Request war, weil die Seite so schnell neu geladen wurde.

Und du hast Recht, das sieht nach ziemlich viel Arbeit für einen relativ kleinen Effekt aus. Wenn du bereits eine fertige Lösung in der Schublade hast, freue ich mich über deinen PR. Ansonsten werden wir das wohl erstmal nicht ändern, es sei denn, es ändert sich etwas an Contao grundlegend.

**Comment by trilobit-gmbh** [comment]
btw.: Du kannst dafür auch einfach Haste nutzen und dir die Implementierung der Toggle-Funktion komplett sparen:

```PHP
$GLOBALS['TL_DCA']['tl_calendar_events']['list']['operations']['feature'] = [
    'label' => &$GLOBALS['TL_LANG']['tl_calendar_events']['feature'],
    'attributes' => 'onclick="Backend.getScrollOffset();"',
    'haste_ajax_operation' => [
        'field' => 'featured',
        'options' => [
            [
                'value' => '',
                'icon' => 'featured_.svg',
            ],
            [
                'value' => '1',
                'icon' => 'featured.svg',
            ],
        ],
    ],
];
```

https://github.com/codefog/contao-haste/blob/master/docs/Dca/index.md

**Comment by jankout** [comment]
Hallo, ich wollte fragen, ob es bald korrigiert wird?
