### ISSUE TITLE
BE: Modul Eventliste: Option "Verkürzte Darstellung" ohne Funktion

### ISSUE THREAD

**Issue by trilobit-gmbh** [ErdmannFreunde/calendar_feature#7]
Contao 4.4.20
Keine weiteren Erweiterungen/Bundles die die Events erweitern/ergänzen/anpassen

Unabhängig davon, ob die Option gesetzt ist, werden "alle" Wiederholungen eines Termins angezeigt.

**Comment by denniserdmann** [comment]
Ich werde mir das nächste Woche mal genauer anschauen, genauso wie #6

**Comment by denniserdmann** [comment]
Habe nun doch schonmal einen ersten Blick darauf werfen können. Ich habe die beiden Fehler nicht nachvollziehen können, allerdings habe ich hier auch nur eine Contao Version 4.4.21 als Vergleich.

Ist die Extension Version aktuell? (Sollte Version 1.0.2 sein) Können andere Einstellungen in Kombination vielleicht den Fehler verursachen? Hier zum Vergleich mal meine Einstellungen, mit denen ich es getestet habe:

![image](https://user-images.githubusercontent.com/3773697/45165199-92554b00-b1f4-11e8-97a4-96f46441efda.png)

In Anbetracht der Tatsache, dass das Hervorheben-Icon nicht funktioniert, könnten die Fehler vielleicht auch an ganz anderer Stelle liegen, dazu bräuchten wir aber mehr Infos.

**Comment by trilobit-gmbh** [comment]
Hallo, vielen Dank für das erste Feedback.

Hier ein paar weitere Infos zum System:
- Contao 4.4.23
- Symfony 3.4.15
- PHP 7.1.10

![auswahl_008](https://user-images.githubusercontent.com/7868402/45211006-7784e400-b291-11e8-9e80-68dc3fa2ce84.jpg)


Das Archiv ist wie folgt konfiguriert:

![auswahl_002](https://user-images.githubusercontent.com/7868402/45211170-e2ceb600-b291-11e8-8c0d-6f59985e61f0.jpg)

Ein Event ist wie folgt konfiguriert; das fragliche ist hervorgehoben.

![auswahl_003](https://user-images.githubusercontent.com/7868402/45211204-f712b300-b291-11e8-8533-99c8bb782834.jpg)

Das Modul für die Anzeige ist wie folgt konfiguriert:

![auswahl_005](https://user-images.githubusercontent.com/7868402/45211254-127dbe00-b292-11e8-85db-697efe817f43.jpg)

Im Frontend habe ich dann folgende Ausgabe: Das Event wird zu allen Wiederholungen angezeigt.

**Comment by trilobit-gmbh** [comment]
Jetzt, wo ich das schreibe sehe ich den Fehler - er sitzt an der Tastatur... - SORRY -

Eine Wiederholung ist kein mehrtägiges Event, sondern zu jeder Wiederholung ein neues Event. Und genau so wird es auch angezeigt und ausgegeben.

Deine Erweiterung ist Super, funktioniert und hat auch schon sehr geholfen. Den Bug an der Tastatur kannst Du nicht korrigieren.

Danke für die Mühe (Asche auf mein Haupt).

Viele Grüße
Peter

**Comment by denniserdmann** [comment]
Hilfe zur Selbsthilfe 😉
Gut, dass du den Fehler selbst finden konntest.
