### ISSUE TITLE
Rechte-Problem: Hervorheben als Redakteuer nicht möglich

### ISSUE THREAD

**Issue by V15** [ErdmannFreunde/calendar_feature#8]
Ich habe die Erweiterung unter Contao 4.4.24 installiert.

Als Admin funktioniert die Erweiterung wie gewünscht, aber als Redakteur bekommt man nach dem anklicken des Sterns die folgende Fehlermeldung:

> Forbidden
Invalid command "feature".

Im Log steht folgendes:

> [2019-03-01 11:53:40] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Invalid command \"feature\". at /html/contao-2018/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:106, Contao\\CoreBundle\\Exception\\AccessDeniedException(code: 0): Invalid command \"feature\". at /html/contao-2018/var/cache/prod/contao/dca/tl_calendar_events.php:643)"} []

Sobald ich aus dem Redakteur einen Admin mache funktioniert es, aber egal was ich dem Redakteur alles freigebe, erscheint immer die Fehlermeldung.

**Comment by denniserdmann** [comment]
Ich denke, wir haben den Fehler gefunden und behoben. Magst du die aktuelle Version im Develop-Branch mal testen und mir Bescheid geben?

**Comment by V15** [comment]
Gerne, wenn du mir sagst wie ich das mache...
Was muss ich im Contao Manager einstellen damit er sich diese Version holt?
Oder muss ich die hier downloaden und manuell hinzufügen?

**Comment by V15** [comment]
Da es sich ja nur um die Änderung von einem Befehl in einer Datei handelt, habe ich das nun einfach manuell gemacht: Funktioniert!

Besten Dank.

**Comment by LinkingYou** [comment]
Fixed 6e62abbefb2299aa74fee9b3152b5b907987131e
